    import LiterateLean
    import QASM
    open scoped LiterateLean

# Verified remote-CNOT routing from `qasm!`

This demonstration treats programs produced by the inline OpenQASM DSL as the proof inputs. It
shows that a four-CNOT route on a three-wire line has the same reversible basis-state semantics as
a remote CNOT, restores the middle wire, obeys the line connectivity, incurs exactly three extra
CNOTs, and is optimal among circuits built from directed adjacent CNOTs.

The semantic claim is intentionally scoped to the CNOT-only fragment. Such a circuit denotes a
permutation of computational basis states, so Boolean-state equality is the complete semantics of
this reversible fragment; no state-vector simulator or unproved amplitude model is involved.

```mermaid
flowchart LR
    DSL["qasm! source"] --> IR["canonical QASM.IR.Program"]
    IR --> Decode["checked CNOT decoder"]
    Decode --> Basis["basis-state semantics"]
    IR --> Cost["QASM.Cost.measure"]
    Basis --> Correct["routing correctness"]
    Basis --> Search["finite optimality proof"]
    Cost --> Overhead["exact overhead"]
```

## The two QASM programs

The direct program expresses the desired logical operation but couples wires zero and two. The
routed program uses only the edges between consecutive wires. Disabling one generated-declaration
linter keeps the standalone demonstration warning-free; it does not change either QASM program.

```lean
set_option linter.unusedVariables false in
qasm! DirectRemoteCNOT {
  OPENQASM 3.0;
  include "stdgates.inc";
  qubit[3] q;
  cx q[0], q[2];
}

set_option linter.unusedVariables false in
qasm! RoutedRemoteCNOT {
  OPENQASM 3.0;
  include "stdgates.inc";
  qubit[3] q;
  cx q[0], q[1];
  cx q[1], q[2];
  cx q[0], q[1];
  cx q[1], q[2];
}

#html RoutedRemoteCNOT.program

namespace Demo

open QASM.IR
```

## A checked decoder for the proof fragment

`CnotGate` stores two bounded wire indices. The decoder consumes the canonical IR generated by
`qasm!`; it does not repeat the source circuit in a separate trusted representation. It accepts
exactly one three-qubit allocation followed by unmodified, unparameterized `cx` applications with
literal in-range indices. Any other operation, dynamic index, physical operand, modifier, arity, or
allocation width makes decoding fail.

```lean
structure CnotGate where
  control : Fin 3
  target : Fin 3
  deriving Repr, BEq, DecidableEq

private def operandIndex (expected : VarId) : QuantumOperand → Option (Fin 3)
  | .wire actual indices false =>
      if actual != expected then none
      else
        match indices.toList with
        | [index] =>
            match index.node with
            | .intLit (.ofNat value) =>
                if h : value < 3 then some ⟨value, h⟩ else none
            | _ => none
        | _ => none
  | _ => none

private def extractCnot (qubits : VarId) : Proc → Option CnotGate
  | .operation (.apply gate operands) =>
      if gate.target != .cx || !gate.parameters.isEmpty || !gate.modifiers.isEmpty then none
      else
        match operands.toList with
        | [control, target] => do
            let control ← operandIndex qubits control
            let target ← operandIndex qubits target
            pure { control, target }
        | _ => none
  | _ => none

def extractCnotProgram (program : Program) : Option (List CnotGate) :=
  match program.body with
  | .sequence steps =>
      match steps.toList with
      | .operation (.allocate declaration) :: rest =>
          if declaration.size != 3 then none
          else rest.mapM (extractCnot declaration.var)
      | _ => none
  | _ => none

def remoteGate : CnotGate := ⟨0, 2⟩

def routedGates : List CnotGate :=
  [⟨0, 1⟩, ⟨1, 2⟩, ⟨0, 1⟩, ⟨1, 2⟩]

theorem direct_extract :
    extractCnotProgram DirectRemoteCNOT.program = some [remoteGate] := by
  decide

theorem routed_extract :
    extractCnotProgram RoutedRemoteCNOT.program = some routedGates := by
  decide
```

The two extraction theorems are the link to the DSL. If parsing or lowering changed either
canonical program, these proofs would have to be re-established rather than silently continuing to
prove a theorem about a hand-written shadow circuit.

## Reversible basis-state semantics

A three-wire basis state is a Boolean triple. Applying CNOT replaces its target by the XOR of the
old target and control. `evalProgram` first runs the checked IR decoder, so unsupported QASM cannot
acquire an invented Boolean meaning.

```lean
structure Basis3 where
  q0 : Bool
  q1 : Bool
  q2 : Bool
  deriving Repr, BEq, DecidableEq

def Basis3.get (state : Basis3) (wire : Fin 3) : Bool :=
  match wire.val with
  | 0 => state.q0
  | 1 => state.q1
  | _ => state.q2

def Basis3.set (state : Basis3) (wire : Fin 3) (value : Bool) : Basis3 :=
  match wire.val with
  | 0 => { state with q0 := value }
  | 1 => { state with q1 := value }
  | _ => { state with q2 := value }

def CnotGate.apply (gate : CnotGate) (state : Basis3) : Basis3 :=
  state.set gate.target (Bool.xor (state.get gate.target) (state.get gate.control))

def evalCircuit (gates : List CnotGate) (input : Basis3) : Basis3 :=
  gates.foldl (fun state gate => gate.apply state) input

def evalProgram (program : Program) (input : Basis3) : Option Basis3 :=
  match extractCnotProgram program with
  | some gates => some (evalCircuit gates input)
  | none => none

def remoteSpec (input : Basis3) : Basis3 :=
  { input with q2 := Bool.xor input.q2 input.q0 }
```

For input $`(a,b,c)`$, the common specification is $`(a,b,c\mathbin{\oplus}a)`$. The proofs split
only the eight possible basis inputs; all circuit steps still come from the lowered QASM programs.

```lean
theorem direct_correct (input : Basis3) :
    evalProgram DirectRemoteCNOT.program input = some (remoteSpec input) := by
  cases input with
  | mk q0 q1 q2 => cases q0 <;> cases q1 <;> cases q2 <;> decide

theorem routed_correct (input : Basis3) :
    evalProgram RoutedRemoteCNOT.program input = some (remoteSpec input) := by
  cases input with
  | mk q0 q1 q2 => cases q0 <;> cases q1 <;> cases q2 <;> decide

theorem routed_eq_direct (input : Basis3) :
    evalProgram RoutedRemoteCNOT.program input =
      evalProgram DirectRemoteCNOT.program input := by
  rw [routed_correct, direct_correct]
```

## Workspace restoration and line connectivity

The semantic specification leaves `q1` unchanged, giving the workspace-restoration theorem for
every basis input. Connectivity is checked separately on the extracted IR: an edge is permitted
exactly when its endpoints differ by one.

```lean
theorem routed_restores_middle (input : Basis3) :
    (evalProgram RoutedRemoteCNOT.program input).map Basis3.q1 = some input.q1 := by
  rw [routed_correct]
  rfl

def CnotGate.onLine (gate : CnotGate) : Bool :=
  gate.control.val + 1 == gate.target.val || gate.target.val + 1 == gate.control.val

def respectsLine (program : Program) : Bool :=
  match extractCnotProgram program with
  | some gates => gates.all CnotGate.onLine
  | none => false

theorem direct_violates_line : respectsLine DirectRemoteCNOT.program = false := by
  decide

theorem routed_respects_line : respectsLine RoutedRemoteCNOT.program = true := by
  decide
```

Thus the direct circuit has the desired action but violates the hardware graph, whereas the routed
circuit preserves that action and satisfies the graph without assuming a clean middle wire.

## Exact static cost

The cost results use the project-wide `QASM.Cost.measure` traversal on each generated `Program`.
They therefore validate both the source-level application count and the primitive CNOT
classification used by the shared static report.

```lean
def directMetrics := QASM.Cost.measure DirectRemoteCNOT.program

def routedMetrics := QASM.Cost.measure RoutedRemoteCNOT.program

theorem direct_cnot_count : directMetrics.resources.gates.cnot = 1 := by
  decide

theorem routed_cnot_count : routedMetrics.resources.gates.cnot = 4 := by
  decide

theorem routing_overhead :
    routedMetrics.resources.gates.cnot = directMetrics.resources.gates.cnot + 3 := by
  decide
```

## Four CNOTs are optimal

There are four directed nearest-neighbor CNOTs on the line. Encoding them as a finite inductive
type makes every list an adjacent circuit by construction. The reference semantics remains the
remote operation extracted from the direct QASM program and proved above.

```lean
inductive AdjacentCnot where
  | c01
  | c10
  | c12
  | c21
  deriving Repr, BEq, DecidableEq

def AdjacentCnot.gate : AdjacentCnot → CnotGate
  | .c01 => ⟨0, 1⟩
  | .c10 => ⟨1, 0⟩
  | .c12 => ⟨1, 2⟩
  | .c21 => ⟨2, 1⟩

def evalAdjacent (circuit : List AdjacentCnot) (input : Basis3) : Basis3 :=
  circuit.foldl (fun state gate => gate.gate.apply state) input

def allBasisStates : List Basis3 :=
  [ ⟨false, false, false⟩, ⟨false, false, true⟩
  , ⟨false, true, false⟩, ⟨false, true, true⟩
  , ⟨true, false, false⟩, ⟨true, false, true⟩
  , ⟨true, true, false⟩, ⟨true, true, true⟩ ]

def sameAsRemote (circuit : List AdjacentCnot) : Bool :=
  allBasisStates.all fun input => decide (evalAdjacent circuit input = remoteSpec input)

theorem allBasisStates_complete (input : Basis3) : input ∈ allBasisStates := by
  cases input with
  | mk q0 q1 q2 => cases q0 <;> cases q1 <;> cases q2 <;> simp [allBasisStates]

theorem sameAsRemote_eq_true_iff (circuit : List AdjacentCnot) :
    sameAsRemote circuit = true ↔
      ∀ input, evalAdjacent circuit input = remoteSpec input := by
  simp only [sameAsRemote, List.all_eq_true, decide_eq_true_eq]
  constructor
  · intro agrees input
    exact agrees input (allBasisStates_complete input)
  · intro agrees input _
    exact agrees input
```

`allBasisStates_complete` proves that the Boolean check covers the whole semantic domain. The
shorter-circuit theorem then performs a complete structural split: lengths zero through three give
$`1+4+4^2+4^3=85`$ adjacent circuits, while the fourth-cons case contradicts the length bound.

```lean
def routedAdjacent : List AdjacentCnot := [.c01, .c12, .c01, .c12]

theorem routedAdjacent_matches_program :
    extractCnotProgram RoutedRemoteCNOT.program =
      some (routedAdjacent.map AdjacentCnot.gate) := by
  decide

theorem routed_adjacent_correct : sameAsRemote routedAdjacent = true := by
  decide

theorem no_shorter_adjacent_circuit (circuit : List AdjacentCnot)
    (shorter : circuit.length < 4) : sameAsRemote circuit = false := by
  rcases circuit with _ | ⟨first, rest⟩
  · decide
  rcases rest with _ | ⟨second, rest⟩
  · cases first <;> decide
  rcases rest with _ | ⟨third, rest⟩
  · cases first <;> cases second <;> decide
  rcases rest with _ | ⟨fourth, rest⟩
  · cases first <;> cases second <;> cases third <;> decide
  · simp only [List.length_cons] at shorter
    omega

theorem no_shorter_adjacent_implements_remote (circuit : List AdjacentCnot)
    (shorter : circuit.length < 4) :
    ¬∀ input, evalAdjacent circuit input = remoteSpec input := by
  intro implements
  have agrees : sameAsRemote circuit = true :=
    (sameAsRemote_eq_true_iff circuit).2 implements
  rw [no_shorter_adjacent_circuit circuit shorter] at agrees
  exact Bool.false_ne_true agrees

theorem routed_is_optimal :
    extractCnotProgram RoutedRemoteCNOT.program =
        some (routedAdjacent.map AdjacentCnot.gate) ∧
      sameAsRemote routedAdjacent = true ∧
      ∀ circuit,
        circuit.length < routedAdjacent.length →
          ¬∀ input, evalAdjacent circuit input = remoteSpec input := by
  refine ⟨routedAdjacent_matches_program, routed_adjacent_correct, ?_⟩
  intro circuit shorter
  exact no_shorter_adjacent_implements_remote circuit
    (by simpa [routedAdjacent] using shorter)

end Demo
```

The final theorem packages the end-to-end claim: the actual routed QASM program decodes to the
four-gate adjacent implementation, realizes the remote operation on every basis state, and no
shorter circuit over the complete nearest-neighbor CNOT library can do so.

<!--
vim: set filetype=markdown :
Local Variables:
mode: markdown
End:
-->
